name: Main Workflow
run-name: ${{ github.actor }} has triggered Main Workflow from a ${{ github.event_name }} event
on: [ push, pull_request ]
jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout and clone repository branch ${{ github.ref }}
#        uses: actions/checkout@v4
#      - name: Create app.properties configuration file
#        run: echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > app.properties
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - run: echo "The build job's status is ${{ job.status }}."
#  unit-test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout and clone repository branch ${{ github.ref }}
#        uses: actions/checkout@v4
#      - name: Create app.properties configuration file
#        run: echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > app.properties
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run release unit tests
#        run: ./gradlew testReleaseUnitTest
#      - run: echo "The unit-test job's status is ${{ job.status }}."
  instrumented-test:
#    needs: build
    timeout-minutes: 20
    runs-on: macos-latest
    env:
      ANDROID_ARCH: x86_64
      ANDROID_TARGET: google_apis_playstore
      API_LEVEL: 33
      ANDROID_BUILD_TOOLS_VERSION: 33.0.2
      ANDROID_SDK_PACKAGES: system-images;android-33;google_apis_playstore;x86_64 platforms;android-33 build-tools;33.0.2 platform-tools emulator
      EMULATOR_TIMEOUT: 350
      EMULATOR_NAME: nexus
    steps:
      - uses: actions/checkout@v3

      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

      - name: Install Sdk
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Build emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

      - name: Launch emulator
        run: |
          ls -lah
          chmod +x ./start_emu_headless.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./start_emu_headless.sh