name: Main Workflow
run-name: ${{ github.actor }} has triggered Main Workflow from a ${{ github.event_name }} event
on: [ push, pull_request ]
jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout and clone repository branch ${{ github.ref }}
#        uses: actions/checkout@v4
#      - name: Create app.properties configuration file
#        run: echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > app.properties
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - run: echo "The build job's status is ${{ job.status }}."
#  unit-test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout and clone repository branch ${{ github.ref }}
#        uses: actions/checkout@v4
#      - name: Create app.properties configuration file
#        run: echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > app.properties
#      - name: Setup JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run release unit tests
#        run: ./gradlew testReleaseUnitTest
#      - run: echo "The unit-test job's status is ${{ job.status }}."
  android_tests:
    runs-on: [ macos-12 ]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest