name: Checkout and Build Project
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout and clone repository branch ${{ github.ref }}
#        uses: actions/checkout@v4
      - name: Create app.properties configuration file
        run: echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > app.properties
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "The build job's status is ${{ job.status }}."
